// Writes the public "mock interview" page content from the interviewer's own question banks, so what
// those pages describe is exactly what the interviewer asks. Run after editing src/interview/roleBanks.ts:
//   npx tsx scripts/export-role-content.ts
import "../src/testing/setup";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { FORMAT_PRESETS } from "../src/interview/plan";
import { ALL_PROBLEMS } from "../src/interview/problems";
import { BEHAVIORAL_BANK, ROLE_BANKS } from "../src/interview/roleBanks";

const out = resolve(import.meta.dirname, "../../frontend/src/content/roles.generated.ts");

const roles = ROLE_BANKS.map((bank) => ({
    slug: bank.slug,
    role: bank.role,
    summary: bank.summary,
    focusAreas: bank.focusAreas,
    codingTopics: [...new Set(bank.codingTags)],
    // A representative spread across levels: the question, and what a strong answer covers.
    sampleQuestions: bank.technical.slice(0, 8).map((q) => ({ question: q.question, skill: q.skill, lookFor: q.lookFor, level: ["intern", "junior", "mid", "senior", "staff"][q.minLevel] })),
    designPrompts: bank.design.map((d) => ({ title: d.title, prompt: d.prompt })),
}));

const formats = Object.entries(FORMAT_PRESETS).map(([id, p]) => ({ id, label: p.label, minutes: p.minutes, description: p.description }));
const behavioral = BEHAVIORAL_BANK.slice(0, 5).map((b) => ({ topic: b.topic, question: b.question }));
const stats = {
    problems: ALL_PROBLEMS.length,
    languages: ["JavaScript", "TypeScript", "Python", "C++", "Java"],
    roles: roles.length,
};

const header = "// Generated by backend/scripts/export-role-content.ts from the interviewer's question banks. Do not edit by hand.\n";
const body = `export interface RoleContent {
    slug: string;
    role: string;
    summary: string;
    focusAreas: string[];
    codingTopics: string[];
    sampleQuestions: Array<{ question: string; skill: string; lookFor: string[]; level: string | undefined }>;
    designPrompts: Array<{ title: string; prompt: string }>;
}

export const ROLE_CONTENT: RoleContent[] = ${JSON.stringify(roles, null, 4)};

export const FORMAT_CONTENT = ${JSON.stringify(formats, null, 4)} as const;

export const BEHAVIORAL_SAMPLES = ${JSON.stringify(behavioral, null, 4)} as const;

export const PRODUCT_STATS = ${JSON.stringify(stats, null, 4)} as const;
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, header + body);
console.log(`Wrote ${roles.length} roles to ${out}`);
