// Generated by backend/scripts/export-role-content.ts from the interviewer's question banks. Do not edit by hand.
export interface RoleContent {
    slug: string;
    role: string;
    summary: string;
    focusAreas: string[];
    codingTopics: string[];
    sampleQuestions: Array<{ question: string; skill: string; lookFor: string[]; level: string | undefined }>;
    designPrompts: Array<{ title: string; prompt: string }>;
}

export const ROLE_CONTENT: RoleContent[] = [
    {
        "slug": "frontend-engineer",
        "role": "Frontend Engineer",
        "summary": "For candidates building interfaces in JavaScript or TypeScript: rendering, state, performance and accessibility.",
        "focusAreas": [
            "Browser rendering and the event loop",
            "React state and performance",
            "Accessibility",
            "Web performance and Core Web Vitals",
            "Security on the client"
        ],
        "codingTopics": [
            "array",
            "string",
            "hash-map",
            "stack",
            "two-pointers"
        ],
        "sampleQuestions": [
            {
                "question": "Walk me through what happens between typing a URL and seeing a rendered page, focusing on the browser.",
                "skill": "Browser internals",
                "lookFor": [
                    "DNS, TCP and TLS, then the HTTP request",
                    "HTML parsed into the DOM, CSS into the CSSOM",
                    "Render tree, layout, paint and compositing",
                    "Render-blocking CSS and scripts"
                ],
                "level": "intern"
            },
            {
                "question": "Explain the JavaScript event loop, and how microtasks differ from macrotasks.",
                "skill": "Event loop",
                "lookFor": [
                    "Call stack and task queues",
                    "Promises run as microtasks before the next macrotask",
                    "setTimeout versus promise ordering",
                    "Long tasks block rendering"
                ],
                "level": "intern"
            },
            {
                "question": "How do closures work, and can you describe a bug they can cause?",
                "skill": "Closures",
                "lookFor": [
                    "A function keeps access to its defining scope",
                    "The classic loop-variable bug with var",
                    "Stale closures in React hooks"
                ],
                "level": "intern"
            },
            {
                "question": "How does React decide what to re-render, and how would you find and fix needless re-renders in a slow screen?",
                "skill": "React rendering",
                "lookFor": [
                    "State and prop changes trigger renders; keys and reconciliation",
                    "Profiling before optimising",
                    "memo, useMemo and useCallback, and their cost",
                    "Splitting state, lifting or colocating it, virtualising long lists"
                ],
                "level": "junior"
            },
            {
                "question": "How would you make a custom dropdown accessible?",
                "skill": "Accessibility",
                "lookFor": [
                    "Correct roles and ARIA states",
                    "Full keyboard operation and focus management",
                    "Screen reader announcements",
                    "Contrast and visible focus"
                ],
                "level": "junior"
            },
            {
                "question": "Explain CSS specificity and the box model, and how you would build a layout that works from phones to wide monitors.",
                "skill": "CSS layout",
                "lookFor": [
                    "Specificity order and why to keep it low",
                    "Box sizing, margin collapse",
                    "Flexbox and grid, fluid units, container or media queries"
                ],
                "level": "intern"
            },
            {
                "question": "How do you manage state in a large front-end application? When do you reach for a global store versus local state or a server-cache library?",
                "skill": "State management",
                "lookFor": [
                    "Local first, lift only when needed",
                    "Server state is different from client state",
                    "Trade-offs of stores like Redux or Zustand",
                    "Derived state and normalisation"
                ],
                "level": "mid"
            },
            {
                "question": "What are the Core Web Vitals, and how would you improve LCP and INP on a heavy page?",
                "skill": "Web performance",
                "lookFor": [
                    "What LCP, INP and CLS measure",
                    "Image and font loading, code splitting, caching",
                    "Reducing main-thread work and hydration cost",
                    "Measuring in the field, not just in the lab"
                ],
                "level": "mid"
            }
        ],
        "designPrompts": [
            {
                "title": "Collaborative document editor",
                "prompt": "Design the front-end architecture of a simplified collaborative document editor, where several people edit the same document at once."
            },
            {
                "title": "Infinite news feed",
                "prompt": "Design an infinite-scrolling news feed with images and live updates."
            }
        ]
    },
    {
        "slug": "backend-engineer",
        "role": "Backend Engineer",
        "summary": "For candidates building services and APIs: data modelling, concurrency, reliability and scaling.",
        "focusAreas": [
            "API design and idempotency",
            "Databases, indexing and transactions",
            "Caching and queues",
            "Concurrency and performance",
            "Authentication and security"
        ],
        "codingTopics": [
            "hash-map",
            "array",
            "graph",
            "heap",
            "dynamic-programming"
        ],
        "sampleQuestions": [
            {
                "question": "How does a database index work, and when would the query planner ignore one?",
                "skill": "Database indexing",
                "lookFor": [
                    "B-tree structure and how it speeds lookups",
                    "Selectivity, leftmost-prefix rule, covering indexes",
                    "The write and storage cost of indexes",
                    "Using EXPLAIN to check"
                ],
                "level": "intern"
            },
            {
                "question": "Compare REST, gRPC and GraphQL. When would you choose each?",
                "skill": "API styles",
                "lookFor": [
                    "Resource model versus RPC versus client-shaped queries",
                    "Payload size, streaming, tooling, browser support",
                    "Caching and versioning implications"
                ],
                "level": "intern"
            },
            {
                "question": "What is a database transaction, and what problems do isolation levels solve? Give a lost-update example.",
                "skill": "Transactions",
                "lookFor": [
                    "ACID basics",
                    "Dirty, non-repeatable and phantom reads",
                    "Lost update and how to prevent it: locking or optimistic versioning",
                    "Cost of higher isolation"
                ],
                "level": "junior"
            },
            {
                "question": "Design a payment endpoint that is safe if the client retries the request.",
                "skill": "Idempotency",
                "lookFor": [
                    "Idempotency keys stored with the result",
                    "Handling concurrent duplicates",
                    "Retry-safe status codes",
                    "Exactly-once is really at-least-once plus idempotency"
                ],
                "level": "junior"
            },
            {
                "question": "Explain cache-aside versus write-through caching, and how you handle invalidation and stampedes.",
                "skill": "Caching",
                "lookFor": [
                    "When each pattern fits",
                    "TTLs, explicit invalidation, versioned keys",
                    "Thundering herd: locking, request coalescing, jittered expiry"
                ],
                "level": "mid"
            },
            {
                "question": "When would you put a message queue between two services? Discuss delivery guarantees.",
                "skill": "Messaging",
                "lookFor": [
                    "Decoupling, buffering bursts, retries",
                    "At-most-once, at-least-once, exactly-once",
                    "Ordering, partitions, dead-letter queues",
                    "Idempotent consumers"
                ],
                "level": "mid"
            },
            {
                "question": "Sessions or JWTs? How do you handle refresh and revocation?",
                "skill": "Authentication",
                "lookFor": [
                    "Stateful versus stateless trade-offs",
                    "Short-lived access tokens and rotating refresh tokens",
                    "Revocation, storage location, CSRF and XSS exposure"
                ],
                "level": "junior"
            },
            {
                "question": "Design a rate limiter. Compare token bucket with sliding window.",
                "skill": "Rate limiting",
                "lookFor": [
                    "Algorithms and their burst behaviour",
                    "Where state lives; shared store for many instances",
                    "Per-user versus per-IP, and headers returned"
                ],
                "level": "mid"
            }
        ],
        "designPrompts": [
            {
                "title": "URL shortener",
                "prompt": "Design a URL shortening service that handles billions of redirects."
            },
            {
                "title": "Notification service",
                "prompt": "Design a service that sends email, push and SMS notifications on behalf of many products."
            }
        ]
    },
    {
        "slug": "full-stack-developer",
        "role": "Full Stack Developer",
        "summary": "For candidates who work across the browser, the API and the database and need to reason about the whole request path.",
        "focusAreas": [
            "The full request path",
            "API and data modelling",
            "State and authentication",
            "Performance end to end",
            "Testing and deployment"
        ],
        "codingTopics": [
            "array",
            "string",
            "hash-map",
            "stack",
            "graph"
        ],
        "sampleQuestions": [
            {
                "question": "Trace a single user action, like clicking Save, from the button to the database and back. Where can it fail?",
                "skill": "Request path",
                "lookFor": [
                    "Event handler, request, validation on both sides",
                    "API, auth check, database write, response",
                    "Loading, error and retry states in the UI",
                    "Idempotency and duplicate submits"
                ],
                "level": "intern"
            },
            {
                "question": "What is the N+1 query problem, and how do you find and fix it?",
                "skill": "Data access",
                "lookFor": [
                    "Symptom: many small queries per request",
                    "Eager loading, joins, batching, DataLoader",
                    "Finding it with query logs or tracing"
                ],
                "level": "junior"
            },
            {
                "question": "Explain CORS. Why does it exist and how do you configure it safely?",
                "skill": "Web security",
                "lookFor": [
                    "Same-origin policy",
                    "Preflight requests and allowed origins",
                    "Credentials and why wildcard origins are unsafe"
                ],
                "level": "junior"
            },
            {
                "question": "Server-side rendering, static generation or client rendering: how do you choose?",
                "skill": "Rendering strategy",
                "lookFor": [
                    "SEO, time to first byte and interactivity trade-offs",
                    "Personalised versus cacheable content",
                    "Hydration cost and caching layers"
                ],
                "level": "mid"
            },
            {
                "question": "Walk me through how you would implement sign-in and keep the user signed in securely.",
                "skill": "Authentication",
                "lookFor": [
                    "Password hashing",
                    "Sessions or tokens, cookie flags, refresh",
                    "CSRF and XSS considerations",
                    "Logout and revocation"
                ],
                "level": "junior"
            },
            {
                "question": "How would you model users, teams and permissions in a relational database?",
                "skill": "Data modelling",
                "lookFor": [
                    "Normalised tables and join tables",
                    "Role or policy based access",
                    "Indexes and migration strategy"
                ],
                "level": "mid"
            },
            {
                "question": "Compare polling, server-sent events and WebSockets for live updates.",
                "skill": "Real-time",
                "lookFor": [
                    "Direction of data, connection cost, scaling",
                    "Reconnects and missed messages",
                    "When polling is good enough"
                ],
                "level": "mid"
            },
            {
                "question": "What would your testing strategy be for a feature that spans the UI, an API and a database?",
                "skill": "Testing",
                "lookFor": [
                    "Unit, integration and end-to-end balance",
                    "Test data and isolation",
                    "What not to test, and flaky tests"
                ],
                "level": "mid"
            }
        ],
        "designPrompts": [
            {
                "title": "Team task tracker",
                "prompt": "Design a team task-tracking app with real-time updates, from the UI through the API to the database."
            }
        ]
    },
    {
        "slug": "devops-sre-engineer",
        "role": "DevOps / SRE Engineer",
        "summary": "For candidates who run production systems: delivery pipelines, infrastructure as code, reliability and incident response.",
        "focusAreas": [
            "CI/CD and safe deployments",
            "Kubernetes and containers",
            "Observability and SLOs",
            "Incident response",
            "Infrastructure as code and Linux"
        ],
        "codingTopics": [
            "string",
            "hash-map",
            "array",
            "graph",
            "stack"
        ],
        "sampleQuestions": [
            {
                "question": "How does a Kubernetes Deployment roll out a new version, and how do you roll back?",
                "skill": "Kubernetes",
                "lookFor": [
                    "ReplicaSets and rolling update strategy",
                    "Readiness and liveness probes, maxSurge and maxUnavailable",
                    "kubectl rollout undo, and why readiness gates matter"
                ],
                "level": "junior"
            },
            {
                "question": "What are SLIs, SLOs and error budgets? How do they change how a team works?",
                "skill": "Reliability",
                "lookFor": [
                    "Definitions with an example",
                    "Error budget policy: freeze releases when burned",
                    "Alerting on burn rate instead of raw thresholds"
                ],
                "level": "junior"
            },
            {
                "question": "A service's latency doubled after a deploy. Walk me through your response.",
                "skill": "Incident response",
                "lookFor": [
                    "Confirm impact, then mitigate first (rollback)",
                    "Golden signals and traces to localise",
                    "Compare the change set, check dependencies",
                    "Communicate, then a blameless postmortem"
                ],
                "level": "junior"
            },
            {
                "question": "Design a CI/CD pipeline. What stages does it have, and how do artifacts move between environments?",
                "skill": "CI/CD",
                "lookFor": [
                    "Build once, promote the same immutable artifact",
                    "Tests, security scans, approvals",
                    "Secrets handling",
                    "Deployment strategies: canary or blue-green"
                ],
                "level": "junior"
            },
            {
                "question": "How do you manage Terraform state on a team, and what goes wrong with drift?",
                "skill": "Infrastructure as code",
                "lookFor": [
                    "Remote state with locking",
                    "Modules and environment separation",
                    "Detecting and reconciling drift, plan review"
                ],
                "level": "mid"
            },
            {
                "question": "A Linux server is slow. What do you check, in what order?",
                "skill": "Linux troubleshooting",
                "lookFor": [
                    "Load, CPU, memory and swap, disk I/O, network",
                    "Tools like top, vmstat, iostat, ss",
                    "Distinguishing saturation from errors"
                ],
                "level": "intern"
            },
            {
                "question": "How do containers isolate a process? What are namespaces and cgroups?",
                "skill": "Containers",
                "lookFor": [
                    "Namespaces limit what a process sees; cgroups limit what it uses",
                    "Images and layers",
                    "Hardening: non-root, read-only filesystem, dropped capabilities"
                ],
                "level": "junior"
            },
            {
                "question": "Explain how a request travels from a client through a load balancer to a pod.",
                "skill": "Networking",
                "lookFor": [
                    "DNS, TLS termination, load balancing algorithm",
                    "Health checks, Services and Ingress",
                    "Where timeouts and retries belong"
                ],
                "level": "mid"
            }
        ],
        "designPrompts": [
            {
                "title": "Zero-downtime platform",
                "prompt": "Design the deployment and observability setup for a platform of fifty services that must deploy several times a day without downtime."
            },
            {
                "title": "Multi-region failover",
                "prompt": "Design a multi-region setup for a stateful service that must survive a full regional outage."
            }
        ]
    },
    {
        "slug": "data-engineer",
        "role": "Data Engineer",
        "summary": "For candidates building pipelines and warehouses: batch and streaming, modelling, quality and orchestration.",
        "focusAreas": [
            "Batch versus streaming",
            "Data modelling and warehouses",
            "SQL and Spark",
            "Data quality and idempotency",
            "Orchestration and lakehouse formats"
        ],
        "codingTopics": [
            "array",
            "hash-map",
            "string",
            "heap",
            "sorting"
        ],
        "sampleQuestions": [
            {
                "question": "When would you choose batch processing over streaming, and the reverse? What does exactly-once really mean?",
                "skill": "Batch vs streaming",
                "lookFor": [
                    "Latency needs versus complexity and cost",
                    "Micro-batch and hybrid designs",
                    "At-least-once plus idempotent writes"
                ],
                "level": "junior"
            },
            {
                "question": "Explain a star schema and how you would handle a slowly changing dimension.",
                "skill": "Data modelling",
                "lookFor": [
                    "Facts and dimensions",
                    "Type 1 versus Type 2 changes",
                    "Surrogate keys, effective dates"
                ],
                "level": "junior"
            },
            {
                "question": "Write, in words, a SQL query that returns the latest order per customer, and one for a running total.",
                "skill": "SQL",
                "lookFor": [
                    "Window functions with ROW_NUMBER or MAX OVER",
                    "Partitioning and ordering",
                    "Alternatives with joins and their cost"
                ],
                "level": "intern"
            },
            {
                "question": "How do you make a pipeline idempotent, and how do you run a backfill safely?",
                "skill": "Pipeline design",
                "lookFor": [
                    "Overwrite partitions or merge on keys",
                    "Deterministic inputs, no wall-clock dependence",
                    "Backfill isolation and late-arriving data"
                ],
                "level": "mid"
            },
            {
                "question": "What causes a Spark shuffle, and how do you deal with skew?",
                "skill": "Spark",
                "lookFor": [
                    "Wide transformations and data movement",
                    "Broadcast joins, salting, repartitioning",
                    "Reading the Spark UI"
                ],
                "level": "mid"
            },
            {
                "question": "How do partitions, consumer groups and offsets work in Kafka?",
                "skill": "Kafka",
                "lookFor": [
                    "Ordering only within a partition",
                    "Consumer group rebalancing",
                    "Offset commits and delivery semantics, retention"
                ],
                "level": "mid"
            },
            {
                "question": "How would you catch bad data before it reaches dashboards?",
                "skill": "Data quality",
                "lookFor": [
                    "Schema and constraint checks, freshness and volume tests",
                    "Contracts with producers",
                    "Alerting and lineage for impact analysis"
                ],
                "level": "junior"
            },
            {
                "question": "What are the benefits of columnar formats like Parquet, and what do table formats such as Iceberg or Delta add?",
                "skill": "Storage formats",
                "lookFor": [
                    "Column pruning, compression, predicate pushdown",
                    "ACID, schema evolution, time travel",
                    "Small files and compaction"
                ],
                "level": "mid"
            }
        ],
        "designPrompts": [
            {
                "title": "Clickstream analytics",
                "prompt": "Design a pipeline that turns website clickstream events into near-real-time dashboards and daily reports."
            },
            {
                "title": "Operational database to warehouse",
                "prompt": "Design replication of a busy operational database into a warehouse with minimal impact on the source."
            }
        ]
    },
    {
        "slug": "mobile-app-developer",
        "role": "Mobile App Developer (React Native/Flutter)",
        "summary": "For candidates building cross-platform mobile apps: rendering, performance, offline behaviour and release management.",
        "focusAreas": [
            "Cross-platform architecture",
            "List and rendering performance",
            "Offline-first and sync",
            "Lifecycle, push and deep links",
            "Security and releases"
        ],
        "codingTopics": [
            "array",
            "string",
            "hash-map",
            "stack",
            "two-pointers"
        ],
        "sampleQuestions": [
            {
                "question": "How does a cross-platform framework render your UI? Compare React Native's architecture with Flutter's engine.",
                "skill": "Architecture",
                "lookFor": [
                    "JavaScript thread, native views and the bridge or JSI and Fabric",
                    "Flutter draws its own widgets via Skia or Impeller",
                    "Consequences for performance and native look"
                ],
                "level": "junior"
            },
            {
                "question": "How do you keep a long scrolling list smooth?",
                "skill": "List performance",
                "lookFor": [
                    "Virtualised lists, stable keys, avoiding re-renders",
                    "Image sizing and caching",
                    "Moving work off the UI thread"
                ],
                "level": "intern"
            },
            {
                "question": "How do you choose a state management approach for a mobile app?",
                "skill": "State management",
                "lookFor": [
                    "Local versus shared state",
                    "Trade-offs of Redux, Zustand, Riverpod or Bloc",
                    "Persisting and restoring state"
                ],
                "level": "junior"
            },
            {
                "question": "Design offline-first behaviour: how do you store data locally and sync it later?",
                "skill": "Offline and sync",
                "lookFor": [
                    "Local database, a queue of pending changes",
                    "Conflict resolution strategy",
                    "Detecting connectivity, retries, UX for stale data"
                ],
                "level": "mid"
            },
            {
                "question": "Explain the app lifecycle, and how push notifications and background work fit into it.",
                "skill": "Lifecycle",
                "lookFor": [
                    "Foreground, background, terminated states",
                    "APNs and FCM flow, silent pushes",
                    "OS limits on background execution"
                ],
                "level": "junior"
            },
            {
                "question": "A crash is reported only in production. How do you investigate?",
                "skill": "Debugging",
                "lookFor": [
                    "Crash reporting with symbolicated stack traces",
                    "Reproducing by device, OS and version",
                    "Staged rollout and rollback or hotfix"
                ],
                "level": "mid"
            },
            {
                "question": "How do you handle navigation and deep links so that a link opens the right screen from any state?",
                "skill": "Navigation",
                "lookFor": [
                    "Route configuration and parameters",
                    "Cold start versus warm start handling",
                    "Auth-gated links"
                ],
                "level": "mid"
            },
            {
                "question": "Where do platform differences bite you, and how do you write native code when you must?",
                "skill": "Platform specifics",
                "lookFor": [
                    "Permissions, keyboards, safe areas, back behaviour",
                    "Native modules or platform channels",
                    "Testing on real devices"
                ],
                "level": "mid"
            }
        ],
        "designPrompts": [
            {
                "title": "Offline-capable chat",
                "prompt": "Design a chat app for mobile that works on flaky networks and offline."
            }
        ]
    },
    {
        "slug": "system-architect-tech-lead",
        "role": "System Architect / Tech Lead",
        "summary": "For candidates who set technical direction: architecture trade-offs, scaling, reliability and leading a team.",
        "focusAreas": [
            "Architecture trade-offs",
            "Consistency and distributed systems",
            "Scaling and reliability",
            "Migration strategy",
            "Leadership and decision making"
        ],
        "codingTopics": [
            "graph",
            "hash-map",
            "dynamic-programming",
            "heap",
            "array"
        ],
        "sampleQuestions": [
            {
                "question": "How do you decide between a monolith and microservices for a team of fifteen?",
                "skill": "Architecture",
                "lookFor": [
                    "Team structure, deployment independence, operational cost",
                    "Start modular, split with evidence",
                    "Data ownership and coupling"
                ],
                "level": "mid"
            },
            {
                "question": "How do you keep data consistent across services without distributed transactions?",
                "skill": "Distributed data",
                "lookFor": [
                    "Sagas and compensations",
                    "The outbox pattern, idempotent consumers",
                    "Where eventual consistency is acceptable"
                ],
                "level": "senior"
            },
            {
                "question": "How would you migrate a legacy system with no downtime?",
                "skill": "Migration",
                "lookFor": [
                    "Strangler fig approach, incremental routing",
                    "Dual writes and data sync risks",
                    "Rollback plan and success metrics"
                ],
                "level": "senior"
            },
            {
                "question": "Where do systems fail as they scale, and how do you find the next bottleneck?",
                "skill": "Scaling",
                "lookFor": [
                    "Measure and model load",
                    "Caching, read replicas, sharding and their costs",
                    "CAP trade-offs in practice"
                ],
                "level": "senior"
            },
            {
                "question": "Describe your approach to reliability: timeouts, retries, circuit breakers and graceful degradation.",
                "skill": "Reliability",
                "lookFor": [
                    "Bounded retries with backoff and jitter",
                    "Bulkheads and load shedding",
                    "Deciding what degrades first"
                ],
                "level": "senior"
            },
            {
                "question": "How do you make and record architectural decisions, and handle disagreement on the team?",
                "skill": "Decision making",
                "lookFor": [
                    "Architecture decision records, options and trade-offs",
                    "Disagree and commit, time-boxing",
                    "Revisiting decisions with new data"
                ],
                "level": "senior"
            },
            {
                "question": "How do you decide what technical debt to pay down, and get buy-in for it?",
                "skill": "Technical debt",
                "lookFor": [
                    "Tie debt to business risk and velocity",
                    "Small continuous investment versus big rewrites",
                    "Making the cost visible"
                ],
                "level": "senior"
            },
            {
                "question": "Walk me through threat modelling a new service.",
                "skill": "Security architecture",
                "lookFor": [
                    "Assets, trust boundaries, attackers",
                    "STRIDE or similar, mitigations",
                    "Least privilege, secrets, auditing"
                ],
                "level": "senior"
            }
        ],
        "designPrompts": [
            {
                "title": "Multi-tenant SaaS platform",
                "prompt": "Design a multi-tenant SaaS platform with per-tenant isolation, usage metering and a path to enterprise customers who need dedicated infrastructure."
            },
            {
                "title": "Global low-latency feed",
                "prompt": "Design a globally distributed activity feed that must feel instant for users on every continent."
            }
        ]
    },
    {
        "slug": "machine-learning-engineer",
        "role": "Machine Learning Engineer",
        "summary": "For candidates who build and ship models: features, training, evaluation and serving them reliably.",
        "focusAreas": [
            "Feature engineering and data leakage",
            "Model evaluation and validation",
            "Training at scale",
            "Serving, latency and drift",
            "Experiment design"
        ],
        "codingTopics": [
            "array",
            "matrix",
            "hash-map",
            "sorting",
            "prefix-sum"
        ],
        "sampleQuestions": [
            {
                "question": "Walk me through building a model to predict something from raw data, end to end.",
                "skill": "ML pipeline",
                "lookFor": [
                    "Problem framing and what 'good' means",
                    "Data collection, cleaning, splitting",
                    "Feature engineering, a baseline before anything fancy",
                    "Evaluation against the baseline"
                ],
                "level": "intern"
            },
            {
                "question": "What is overfitting, and what would make you suspect a model has it?",
                "skill": "Generalisation",
                "lookFor": [
                    "Gap between train and validation performance",
                    "Model complexity versus data size",
                    "Regularisation, more data, simpler model, early stopping"
                ],
                "level": "intern"
            },
            {
                "question": "How do you choose which metric to optimise for a classifier on an imbalanced dataset?",
                "skill": "Evaluation",
                "lookFor": [
                    "Why accuracy misleads on imbalance",
                    "Precision, recall, F1 and the trade-off between them",
                    "Picking the metric from the real cost of each error"
                ],
                "level": "junior"
            },
            {
                "question": "What is data leakage, and how have you caught it in practice?",
                "skill": "Data leakage",
                "lookFor": [
                    "Information from the future or the label leaking into features",
                    "Leakage through preprocessing done before the split",
                    "Time-based splits for time-dependent data"
                ],
                "level": "junior"
            },
            {
                "question": "How would you validate a model before it ever reaches production?",
                "skill": "Validation",
                "lookFor": [
                    "Held-out and cross-validation",
                    "Slicing performance by segment, not just the aggregate",
                    "Sanity checks and a human review of edge cases"
                ],
                "level": "junior"
            },
            {
                "question": "You trained a model that looks great offline, but it's failing in production. How do you debug it?",
                "skill": "Train-serve skew",
                "lookFor": [
                    "Training-serving skew in features or preprocessing",
                    "Data drift versus concept drift",
                    "Checking the pipeline before the model itself"
                ],
                "level": "mid"
            },
            {
                "question": "How would you serve a model that needs a prediction in under 50 milliseconds?",
                "skill": "Serving",
                "lookFor": [
                    "Batch versus online inference",
                    "Model size, quantisation, distillation",
                    "Caching, warm pools, and what happens on a cold start"
                ],
                "level": "mid"
            },
            {
                "question": "How do you design an A/B test to tell whether a new model is actually better?",
                "skill": "Experimentation",
                "lookFor": [
                    "Randomisation unit and guardrail metrics",
                    "Sample size and how long to run it",
                    "Novelty effects and interaction with other experiments"
                ],
                "level": "mid"
            }
        ],
        "designPrompts": [
            {
                "title": "Recommendation system",
                "prompt": "Design a recommendation system for a content platform with tens of millions of users, including how you would measure whether it's working."
            },
            {
                "title": "Fraud detection pipeline",
                "prompt": "Design a system that scores transactions for fraud in real time, where both false positives and false negatives are expensive."
            }
        ]
    },
    {
        "slug": "security-engineer",
        "role": "Security Engineer",
        "summary": "For candidates who secure systems: application security, threat modelling, incident response and secure design.",
        "focusAreas": [
            "Application security (OWASP-style vulnerabilities)",
            "Authentication and authorization",
            "Threat modelling",
            "Incident response",
            "Secure infrastructure and secrets"
        ],
        "codingTopics": [
            "string",
            "hash-map",
            "bit-manipulation",
            "array",
            "stack"
        ],
        "sampleQuestions": [
            {
                "question": "Walk me through what you'd look for reviewing a pull request that adds a new API endpoint accepting user input.",
                "skill": "Code review for security",
                "lookFor": [
                    "Input validation and output encoding",
                    "AuthN versus authZ on the endpoint",
                    "Where the input ends up: a query, a shell, a template"
                ],
                "level": "intern"
            },
            {
                "question": "Explain SQL injection and how modern frameworks prevent it, plus a case where it can still slip through.",
                "skill": "Injection",
                "lookFor": [
                    "Untrusted input reaching a query as code, not data",
                    "Parameterised queries versus string concatenation",
                    "Dynamic table or column names, ORMs used unsafely"
                ],
                "level": "intern"
            },
            {
                "question": "What is XSS, and what's the difference between stored, reflected and DOM-based?",
                "skill": "XSS",
                "lookFor": [
                    "Untrusted content rendered as executable script",
                    "Where each type's payload lives and travels",
                    "Output encoding and a Content Security Policy as defence in depth"
                ],
                "level": "junior"
            },
            {
                "question": "How would you design authentication and session management for a new web app?",
                "skill": "AuthN design",
                "lookFor": [
                    "Password hashing, MFA, account lockout without enabling enumeration",
                    "Session tokens versus stateless tokens, and revocation",
                    "Secure cookie flags, CSRF protection"
                ],
                "level": "junior"
            },
            {
                "question": "Walk me through threat modelling a new feature before it ships.",
                "skill": "Threat modelling",
                "lookFor": [
                    "Assets, entry points, trust boundaries",
                    "STRIDE or an equivalent structured walk",
                    "Turning findings into concrete mitigations, not just a list"
                ],
                "level": "mid"
            },
            {
                "question": "What is SSRF, and why does it matter more once services talk to cloud metadata endpoints?",
                "skill": "SSRF",
                "lookFor": [
                    "Server tricked into making a request on the attacker's behalf",
                    "Cloud metadata endpoints as a common target",
                    "Allow-lists, network segmentation, disabling redirects"
                ],
                "level": "mid"
            },
            {
                "question": "How would you design least-privilege access for a service that touches several internal systems?",
                "skill": "Access control",
                "lookFor": [
                    "Scoped, short-lived credentials over broad standing access",
                    "Service identity and mutual TLS between services",
                    "Auditing who has access to what, and why"
                ],
                "level": "mid"
            },
            {
                "question": "Walk me through your first hour after being paged for a suspected active breach.",
                "skill": "Incident response",
                "lookFor": [
                    "Confirm and scope before acting rashly",
                    "Contain without destroying evidence",
                    "Who gets told, and when, including legal and customers"
                ],
                "level": "senior"
            }
        ],
        "designPrompts": [
            {
                "title": "Secrets and credentials service",
                "prompt": "Design a secrets management system for an organisation with hundreds of services, where a leaked secret must be found and rotated fast."
            },
            {
                "title": "Zero-trust internal network",
                "prompt": "Design access to internal tools for a company moving away from a trusted-internal-network model to zero trust."
            }
        ]
    },
    {
        "slug": "qa-test-engineer",
        "role": "QA / Test Engineer",
        "summary": "For candidates who build confidence in software before and after it ships: test strategy, automation and quality risk.",
        "focusAreas": [
            "Test strategy and coverage",
            "Automation frameworks",
            "Flaky tests and CI reliability",
            "Regression and risk analysis",
            "Bug investigation and reporting"
        ],
        "codingTopics": [
            "array",
            "string",
            "hash-map",
            "two-pointers",
            "sorting"
        ],
        "sampleQuestions": [
            {
                "question": "How do you decide what to cover with unit tests versus integration tests versus end-to-end tests?",
                "skill": "Test strategy",
                "lookFor": [
                    "The test pyramid and why each layer exists",
                    "Speed and reliability trade-offs at each layer",
                    "Not testing the same thing redundantly at every layer"
                ],
                "level": "intern"
            },
            {
                "question": "Given a new feature with an acceptance criteria doc, how do you turn it into a test plan?",
                "skill": "Test planning",
                "lookFor": [
                    "Breaking criteria into concrete test cases",
                    "Edge cases and negative cases, not just the happy path",
                    "Deciding what's worth automating versus checking once"
                ],
                "level": "intern"
            },
            {
                "question": "A test suite that used to be reliable is now flaky. How do you investigate?",
                "skill": "Flaky tests",
                "lookFor": [
                    "Distinguishing a real bug from a bad test",
                    "Common causes: timing, shared state, order dependence",
                    "Quarantine versus fix versus delete, and how you decide"
                ],
                "level": "junior"
            },
            {
                "question": "How do you write tests that don't break every time the implementation changes?",
                "skill": "Maintainable tests",
                "lookFor": [
                    "Testing behaviour and contracts, not internals",
                    "Good use of test doubles versus over-mocking",
                    "Readable failures that say what actually broke"
                ],
                "level": "junior"
            },
            {
                "question": "How would you test a system you can't fully see the internals of, like a third-party integration?",
                "skill": "Black-box testing",
                "lookFor": [
                    "Contract tests against the interface",
                    "Simulating failure modes: timeouts, malformed responses, rate limits",
                    "Monitoring in production as a form of testing"
                ],
                "level": "mid"
            },
            {
                "question": "Walk me through triaging a bug report with a vague description like 'it doesn't work sometimes'.",
                "skill": "Bug investigation",
                "lookFor": [
                    "Getting to a reliable repro before doing anything else",
                    "Narrowing scope: environment, data, timing",
                    "Distinguishing severity from priority"
                ],
                "level": "mid"
            },
            {
                "question": "How do you decide what to automate versus what's better tested manually or exploratorily?",
                "skill": "Automation strategy",
                "lookFor": [
                    "Cost of writing and maintaining automation versus its value",
                    "Where exploratory testing finds things automation won't",
                    "Regression-prone areas as the first automation target"
                ],
                "level": "mid"
            },
            {
                "question": "How would you keep a CI pipeline's test suite fast as the codebase and suite both grow?",
                "skill": "CI performance",
                "lookFor": [
                    "Parallelisation and sharding",
                    "Splitting fast smoke tests from a slower full suite",
                    "Data on which tests actually catch bugs, versus dead weight"
                ],
                "level": "senior"
            }
        ],
        "designPrompts": [
            {
                "title": "End-to-end test infrastructure",
                "prompt": "Design the end-to-end test infrastructure for a web app released several times a day, where slow or flaky tests currently block every release."
            },
            {
                "title": "Load and reliability testing",
                "prompt": "Design a load-testing strategy for a service ahead of a launch expected to bring ten times normal traffic."
            }
        ]
    },
    {
        "slug": "data-scientist",
        "role": "Data Scientist",
        "summary": "For candidates who turn data into decisions: statistics, experimentation, analysis and communicating findings.",
        "focusAreas": [
            "Statistical reasoning",
            "Experiment design",
            "Exploratory data analysis",
            "Communicating uncertainty",
            "Practical modelling"
        ],
        "codingTopics": [
            "array",
            "hash-map",
            "sorting",
            "prefix-sum",
            "two-pointers"
        ],
        "sampleQuestions": [
            {
                "question": "Walk me through how you'd approach a vague ask like 'figure out why signups dropped last month'.",
                "skill": "Analytical approach",
                "lookFor": [
                    "Clarifying the actual question and what decision it feeds",
                    "Looking at the data before forming a theory",
                    "Segmenting to find where the drop is concentrated"
                ],
                "level": "intern"
            },
            {
                "question": "Explain p-values and statistical significance to someone who doesn't have a stats background.",
                "skill": "Statistical reasoning",
                "lookFor": [
                    "What a p-value actually means, and what it does not",
                    "Significance versus practical importance",
                    "The risk of testing many things and finding one by chance"
                ],
                "level": "intern"
            },
            {
                "question": "What is confounding, and how have you dealt with it in an analysis?",
                "skill": "Confounding",
                "lookFor": [
                    "A variable that affects both the supposed cause and the outcome",
                    "Correlation is not causation, with a concrete example",
                    "Controlling for it, or why you couldn't"
                ],
                "level": "junior"
            },
            {
                "question": "How do you decide on sample size before running an experiment?",
                "skill": "Power analysis",
                "lookFor": [
                    "Minimum detectable effect and the trade-off with runtime",
                    "Baseline rate and variance driving the required sample",
                    "What happens if you peek at results early"
                ],
                "level": "junior"
            },
            {
                "question": "You're given a messy dataset with missing values and outliers. How do you approach cleaning it?",
                "skill": "Data cleaning",
                "lookFor": [
                    "Understanding why data is missing before deciding how to handle it",
                    "Outliers as signal versus noise, not automatically deleted",
                    "Documenting cleaning decisions so they're reproducible"
                ],
                "level": "junior"
            },
            {
                "question": "An A/B test shows a statistically significant lift, but the product team is skeptical. How do you build confidence in the result?",
                "skill": "Experiment validation",
                "lookFor": [
                    "Sanity checks: sample ratio mismatch, pre-period balance",
                    "Practical significance versus statistical significance",
                    "Segment consistency and looking for a plausible mechanism"
                ],
                "level": "mid"
            },
            {
                "question": "How do you explain a model or analysis's uncertainty to a stakeholder who wants a single number?",
                "skill": "Communicating uncertainty",
                "lookFor": [
                    "Confidence or credible intervals in plain language",
                    "Framing a range and what drives its width",
                    "Not overstating confidence to seem more useful"
                ],
                "level": "mid"
            },
            {
                "question": "How would you detect that an earlier analysis or dashboard is now giving misleading numbers?",
                "skill": "Data quality",
                "lookFor": [
                    "Monitoring key metrics for unexplained shifts",
                    "Upstream schema or tracking changes as a common cause",
                    "A process for someone to flag a number that looks wrong"
                ],
                "level": "mid"
            }
        ],
        "designPrompts": [
            {
                "title": "Experimentation platform",
                "prompt": "Design the analysis pipeline for a company's A/B testing platform, from an experiment being launched to a trustworthy result reaching the team that ran it."
            },
            {
                "title": "Churn analysis and intervention",
                "prompt": "Design an approach to understand why customers churn and to identify who is at risk before they leave."
            }
        ]
    },
    {
        "slug": "game-developer",
        "role": "Game Developer",
        "summary": "For candidates building games: real-time performance, gameplay systems, engines and the tricky edges of simulation.",
        "focusAreas": [
            "Real-time performance and frame budgets",
            "Game loop and simulation",
            "Memory management",
            "Networking for multiplayer",
            "Engine architecture (Unity/Unreal or custom)"
        ],
        "codingTopics": [
            "matrix",
            "array",
            "hash-map",
            "heap",
            "graph"
        ],
        "sampleQuestions": [
            {
                "question": "Walk me through a game loop and why a fixed timestep matters for simulation.",
                "skill": "Game loop",
                "lookFor": [
                    "Update and render separated, and why",
                    "Delta time and frame-rate independence",
                    "Fixed timestep for physics so behaviour is deterministic"
                ],
                "level": "intern"
            },
            {
                "question": "Why does object pooling matter in a game, and where have you used it?",
                "skill": "Memory and performance",
                "lookFor": [
                    "Allocation and garbage collection cost during gameplay",
                    "Reusing objects like bullets or particles instead of allocating",
                    "The trade-off: pool size versus memory held idle"
                ],
                "level": "intern"
            },
            {
                "question": "How would you find out why a scene is dropping frames?",
                "skill": "Profiling",
                "lookFor": [
                    "Profiling before guessing: CPU, GPU or memory bound",
                    "Draw calls, overdraw, and batching",
                    "Distinguishing a spike from a sustained cost"
                ],
                "level": "junior"
            },
            {
                "question": "Explain the entity-component-system pattern, and when you'd reach for it over classic inheritance.",
                "skill": "Architecture",
                "lookFor": [
                    "Composition over deep inheritance hierarchies",
                    "Data-oriented layout for cache-friendly updates",
                    "When ECS is overkill for a smaller game"
                ],
                "level": "junior"
            },
            {
                "question": "How does collision detection typically work, and how would you speed it up for hundreds of objects?",
                "skill": "Collision and spatial structures",
                "lookFor": [
                    "Broad phase versus narrow phase",
                    "Spatial partitioning: grids, quadtrees or similar",
                    "Trade-offs between accuracy and performance"
                ],
                "level": "mid"
            },
            {
                "question": "How would you design client-server networking for a fast-paced multiplayer game with noticeable latency?",
                "skill": "Multiplayer networking",
                "lookFor": [
                    "Client-side prediction and server reconciliation",
                    "Lag compensation for hit detection",
                    "What the server must remain authoritative over, and why"
                ],
                "level": "mid"
            },
            {
                "question": "How do you manage state that must stay in sync between many players without the network becoming the bottleneck?",
                "skill": "State synchronisation",
                "lookFor": [
                    "Delta compression: sending changes, not full state",
                    "Prioritising what's visible or relevant to each player",
                    "Handling packet loss and out-of-order delivery gracefully"
                ],
                "level": "senior"
            },
            {
                "question": "How would you design a level-of-detail system for a large open world?",
                "skill": "LOD and streaming",
                "lookFor": [
                    "Distance-based detail reduction for meshes and logic",
                    "Streaming assets in and out without a visible hitch",
                    "Balancing visual quality against memory and load"
                ],
                "level": "senior"
            }
        ],
        "designPrompts": [
            {
                "title": "Real-time multiplayer arena",
                "prompt": "Design the client-server architecture for a real-time multiplayer arena game for up to twenty players, where responsiveness matters more than perfect consistency."
            },
            {
                "title": "Open-world streaming",
                "prompt": "Design how a large open-world game streams its world in and out of memory as the player moves through it."
            }
        ]
    }
];

export const FORMAT_CONTENT = [
    {
        "id": "quick",
        "label": "Quick screen",
        "minutes": 20,
        "description": "A short phone-screen: introductions, your background, and one coding problem."
    },
    {
        "id": "standard",
        "label": "Standard loop",
        "minutes": 45,
        "description": "Introductions, background, two coding problems, technical questions from the job description, and behavioral."
    },
    {
        "id": "full",
        "label": "Full loop",
        "minutes": 75,
        "description": "The standard loop plus a third coding problem and a system-design round."
    },
    {
        "id": "drill",
        "label": "Coding drill",
        "minutes": 30,
        "description": "Only data structures and algorithms: four problems back to back with a quick complexity question after each."
    }
] as const;

export const BEHAVIORAL_SAMPLES = [
    {
        "topic": "Disagreement",
        "question": "Tell me about a time you disagreed with a teammate about a technical decision. What happened?"
    },
    {
        "topic": "Failure",
        "question": "Tell me about something that went wrong on a project you worked on. What was your role, and what did you take from it?"
    },
    {
        "topic": "Ambiguity",
        "question": "Describe a time you had to deliver something with unclear requirements. How did you make progress?"
    },
    {
        "topic": "Deadline pressure",
        "question": "Tell me about a time you had to hit a tight deadline. What did you cut, and how did you decide?"
    },
    {
        "topic": "Feedback",
        "question": "Tell me about feedback that was hard to hear. What did you do with it?"
    }
] as const;

export const PRODUCT_STATS = {
    "problems": 101,
    "languages": [
        "JavaScript",
        "TypeScript",
        "Python",
        "C++",
        "Java"
    ],
    "roles": 12
} as const;
